### ISSUE TITLE
would it be possible to emulate the remote and connect to the hub?

### ISSUE THREAD

**Issue by realPilotfish** [joakimjalden/Harmoino#1]
I now have two failing harmony remote controls, some keys do not work anymore.
As those remotes are no longer produced, it is very expensive to get a used one on ebay.
Aside from this, I love my harmony. The hub works fine, I have IR blasters control devices in two more rooms and the integration in environments like home assistant or node red ist just great.

I wonder if it would be possible to kind of emulate a remote with something like an esp32 and use this to bridge bluetooth input devices to the harmony hub.
This way you could grab some bluetooth remote like the G20S PRO BT or similar to pair it to the esp32 and map bluetooth hid events to simulated harmony key presses.

I know the hubs have an API, but the latency should be better emulating the remote.

What do you think?

**Comment by joakimjalden** [comment]
This should be possible but will require a bit work. If you hook up the esp32 to an nRF24L01+ you should be able to receive commands from the BT remote using the esp32s built in bluetooth, translate these to corresponding Harmony codes and messaging protocols on the esp32, and then send them to the hub.

You should start by getting the nRF24L01 network adress of your Hub using the NetworkAdress script. Then use the SimpleHub script to look at the messages sent out by the remote. In principle, sending out the same set of messages from the esp32 should trigger the hub as if a Harmony button was pressed although I don't remember if I ever tried this. There is a bit of of a protocol to it but it is not super advanced and should be mostly explained in the repo ReadMe. You can also find the full set of button codes in the MQTTHub script for the broken buttons. As for interfacing with the BT remote that is something I cannot help you with, but hopefully this is more standard.

Also, if you ever make this work, please let me know. I don't think I have ever gotten confirmation of anyone else successfully using the code.
